---
title: "additional material"
author: "Eyal Grinberg & Yam Rozen"
date: "2023-08-22"
output:
  pdf_document: default
  html_document: default
---

Libraries

```{r, message=FALSE}
library(naniar)
library(dplyr)
library(tidyverse)
library(tidytext)
library(stringdist)
library(ggplot2)
```


Reading Data

```{r, message=FALSE}
data_food_train <- read_csv("data/food_train.csv")
data_nutrients <- read_csv("data/nutrients.csv")
data_food_nutrients <- read_csv("data/food_nutrients.csv")
data_food_test <- read_csv("data/food_test.csv")
```


Data Exploratory references

1 Data food train

1.1 NA values

```{r}
gg_miss_var(data_food_train, show_pct = TRUE)
gg_miss_var(data_food_test, show_pct = TRUE)
gg_miss_var(data_food_nutrients, show_pct = TRUE)
gg_miss_var(data_nutrients, show_pct = TRUE)
```


1.2 household_serving_fulltext distance matrix

```{r}
# Let's create a distance matrix for the household_serving_fulltext variable

household_df <- data_food_train %>% select(household_serving_fulltext, category)
household_df$household_serving_only_unit <- gsub("[0-9[:punct:]]", "",
  household_df$household_serving_fulltext) # drop amounts
household_df$household_serving_only_unit <- 
  household_df$household_serving_only_unit %>% replace_na("NA")
household_serving_unique <- unique(household_df$household_serving_only_unit)
sum(is.na(household_serving_unique))
dists_mat_household <- stringdistmatrix(
  household_serving_unique, household_serving_unique, method = "jw")
dists_mat_household[1:10,1:10] # looks pretty good
clusters_household <- hclust(as.dist(dists_mat_household))
plot(clusters_household)
cuts <- cutree(clusters_household, 75)
cuts [1:100]

# We won't take this idea further.
```


1.3 Description Tokenizing

```{r}
# 1 word

data_train_tokenized_description <- data_food_train %>%
  unnest_tokens(word, description) %>% count(category, word, sort = TRUE)
head(data_train_tokenized_description)
data_train_tokenized_description_grouped_by_cat <- data_train_tokenized_description %>%
  group_by(category) %>% summarise(word, n)
head(data_train_tokenized_description_grouped_by_cat)

# just chocolate category
data_chocolate <- data_train_tokenized_description_grouped_by_cat[
  data_train_tokenized_description_grouped_by_cat$category == "chocolate" , ]
head(data_chocolate)

# 2 words

data_train_tokenized_description_2_tokens <- data_food_train %>% 
  unnest_tokens(bigram, description, token = "ngrams", n = 2) %>%
  count(category, bigram, sort = TRUE)
head(data_train_tokenized_description_2_tokens)
data_train_tokenized_description_grouped_by_cat_2_tokens <-
  data_train_tokenized_description_2_tokens %>% 
  group_by(category) %>% summarise(bigram, n)
head(data_train_tokenized_description_grouped_by_cat_2_tokens)

# just chocolate category
data_chocolate_2_tokens <- data_train_tokenized_description_grouped_by_cat_2_tokens[
  data_train_tokenized_description_grouped_by_cat_2_tokens$category == "chocolate" , ]
head(data_chocolate_2_tokens)
```


1.4 Ingredients Tokenizing


```{r}
# 1 word 

data_train_tokenized_ingredients <- data_food_train %>% unnest_tokens(
  word, ingredients) %>% count(category, word, sort = TRUE)
head(data_train_tokenized_ingredients)
data_train_tokenized_ingredients_grouped_by_cat <- 
  data_train_tokenized_ingredients %>% group_by(category) %>% summarise(word, n)
head(data_train_tokenized_ingredients_grouped_by_cat)

# just chocolate category
data_chocolate_ingrediends <- data_train_tokenized_ingredients_grouped_by_cat[
  data_train_tokenized_ingredients_grouped_by_cat$category == "chocolate" , ]
head(data_chocolate_ingrediends)

# 5 words

data_train_tokenized_ingredients_ngrams_5 <- data_food_train %>% 
  unnest_tokens(word, ingredients, token = "ngrams", n = 5) %>% 
  count(category, word, sort = TRUE)
head(data_train_tokenized_ingredients_ngrams_5)
data_train_tokenized_ingredients_grouped_by_cat_ngrams_5 <-
  data_train_tokenized_ingredients_ngrams_5 %>% 
  group_by(category) %>% summarise(word, n)
head(data_train_tokenized_ingredients_grouped_by_cat_ngrams_5)
# Not very helpful
```


1.5 Brand distance matrix

```{r}
brands_unique <- unique(data_food_train$brand)
length(brands_unique) # 4783
# We can see that there are many different brands, is it possible to merge some of them?
```

```{r}
# Let's create a distance matrix between the brands
dists_mat <- stringdistmatrix(brands_unique, brands_unique, method = "jw")
clusters <- hclust(as.dist(dists_mat))
plot(clusters)
cuts <- cutree(clusters, 3000)
cuts[1:100]

# after watching the results we saw that brands 26 and 65 were clustered to the same cluster.
brands_unique[26]
brands_unique[65]

# after manually scanning the results we noticed that many brands 
# have the following prefixes: inc, ltd, llc, co, corp, company 
num_inc <- sum(str_detect(brands_unique, "inc"))
num_ltd <- sum(str_detect(brands_unique, "ltd"))
num_llc <- sum(str_detect(brands_unique, "llc"))
num_co <- sum(str_detect(brands_unique, "co"))
num_corp <- sum(str_detect(brands_unique, "corp"))
num_company <- sum(str_detect(brands_unique, "company"))
num_inc
num_ltd
num_llc
num_co
num_corp
num_company

# These prefixes make the similarity algorithm find similarities that
# we don't really want, Let's drop them.

words_to_drop <- c(" inc", " ltd", " llc", " co ", "corp", " company")
pattern <- paste(words_to_drop, collapse = "|")
filtered_unique_brands <- gsub(pattern, "", brands_unique)
filtered_unique_brands <- gsub("\\s{2,}", " ", filtered_unique_brands)
length(unique(filtered_unique_brands)) # 4745
# Not a big difference

# Let's create a distance matrix between the filtered brands
dists_mat <- stringdistmatrix(filtered_unique_brands, filtered_unique_brands, method = "jw")
dists_mat[1:10,1:10]
clusters <- hclust(as.dist(dists_mat))
plot(clusters)
cuts <- cutree(clusters, 3000)
cuts[1:100]

```


2 data_nutrients +  data_food_nutrients

2.1 Plots mean amount of each nutrient by category

```{r}
merged_df_nutrients <- merge(data_food_nutrients, data_nutrients,
                             by = "nutrient_id", all.x = TRUE) %>% arrange(idx)

merged_df_nutrients <- merged_df_nutrients[-1]

data_food_test$category <- "unknown"
data_food <- rbind(data_food_train, data_food_test)
merged_df_nutrients <- merge(merged_df_nutrients, data_food[, c(1,8)], 
                             by = "idx", all.x = TRUE)

df_nutrients_mean_by_cat <- merged_df_nutrients %>%
  group_by(category, name) %>% mutate(mean_amount = mean(amount))

nuts_splitted_by_cat <- split(merged_df_nutrients , merged_df_nutrients$category)

cakes_mean_by_nut <- nuts_splitted_by_cat$cakes_cupcakes_snack_cakes %>%
  group_by(name) %>% reframe(mean_amount = mean(amount)) 
choco_mean_by_nut <- nuts_splitted_by_cat$chocolate %>%
  group_by(name) %>% reframe(mean_amount = mean(amount))
popcorn_mean_by_nut <- nuts_splitted_by_cat$popcorn_peanuts_seeds_related_snacks %>% 
  group_by(name) %>% reframe(mean_amount = mean(amount))
candy_mean_by_nut <- nuts_splitted_by_cat$candy %>%
  group_by(name) %>% reframe(mean_amount = mean(amount))
chips_mean_by_nut <- nuts_splitted_by_cat$chips_pretzels_snacks %>%
  group_by(name) %>% reframe(mean_amount = mean(amount))
cookies_mean_by_nut <- nuts_splitted_by_cat$cookies_biscuits %>% 
  group_by(name) %>% reframe(mean_amount = mean(amount))
test_mean_by_nut <- nuts_splitted_by_cat$unknown %>% 
  group_by(name) %>% reframe(mean_amount = mean(amount))
head(cakes_mean_by_nut)

df_list <- list(cakes_mean_by_nut, candy_mean_by_nut, popcorn_mean_by_nut,
  choco_mean_by_nut, chips_mean_by_nut, cookies_mean_by_nut, test_mean_by_nut)

nutrients_mean_amount_with_zero_amounts <- df_list %>% reduce(full_join, by = "name")
colnames(nutrients_mean_amount_with_zero_amounts) <- 
  c("nutrient", "cakes", "candy", "popcorn", "chocolate", "chips", "cookies", "test")

# replace NAs with 0
nutrients_mean_amount_with_zero_amounts[is.na(
  nutrients_mean_amount_with_zero_amounts)] <- 0  

# Visualization

ggplot_nutrients <- function(pivoted_df, start, end) {
  ggplot(data = pivoted_df[start:end,], mapping = aes(x = category, y = mean_amount,
  color = category)) + geom_point() + facet_wrap(. ~ nutrient, scales = "free_y") +
  labs(title = "category vs. nutrient mean amount of each nutrient",
  x = "category", y ="mean_amount") + theme(strip.text.x = element_text(
  size = 10, margin = margin()),axis.text.x.bottom = element_blank(),
  strip.text.y = element_text(size = 20, margin = margin()))
}

nuts_pivoted <- nutrients_mean_amount_with_zero_amounts %>%
  pivot_longer(!nutrient, names_to = "category", values_to = "mean_amount")

ggplot_nutrients(nuts_pivoted, 1, 63)
ggplot_nutrients(nuts_pivoted, 64, 126)
ggplot_nutrients(nuts_pivoted, 127, 189)
ggplot_nutrients(nuts_pivoted, 190, 252)
ggplot_nutrients(nuts_pivoted, 253, 329)
```

