---
title: "additional material for Data Exploratory"
author: "Eyal Grinberg & Yam Rozen"
date: "2023-07-19"
output:
  html_document: default
  pdf_document: default
---
```{r}
knitr::opts_chunk$set(fig.width=8, fig.height=8)
```

packages and libraries

```{r}
if(F){
  install.packages(c("DataExplorer","SmartEDA","explore","tidytext","dataMaid", "explore"))
}
```

```{r}
library(DataExplorer)
library(SmartEDA)
library(tidyverse)
library(dataMaid)
library(dplyr)
library(explore)
library(ggplot2)
library(tidytext)
```

```{r}
data_food_train <- read_csv("data/food_train.csv")
```

```{r, eval=FALSE}
ExpReport(data_food_train, Target = "category", op_file = "Report.html", op_dir = getwd())
```

```{r, eval=FALSE}
makeDataReport(data = data_food_train, output = "html", replace = TRUE)
```

```{r, eval=FALSE}
create_report(data = data_food_train)
```

```{r}
data_nutrients <- read_csv("data/nutrients.csv")
data_food_nutrients <- read_csv("data/food_nutrients.csv")
data_food_test <- read_csv("data/food_test.csv")
```

```{r}
merged_df_nutrients <- merge(data_food_nutrients, data_nutrients, by = "nutrient_id", all.x = TRUE)
merged_df_nutrients <- merged_df_nutrients %>% arrange(idx)
```

```{r}
data_train_tokenized_description <- data_food_train %>% unnest_tokens(word, description) %>% count(category, word, sort = TRUE)
data_train_tokenized_description_grouped_by_cat <- data_train_tokenized_description %>% group_by(category) %>% summarise(word, n)
```

```{r}
data_chocolate <- data_train_tokenized_description_grouped_by_cat[data_train_tokenized_description_grouped_by_cat$category == "chocolate" , ]
data_candy <- data_train_tokenized_description_grouped_by_cat[data_train_tokenized_description_grouped_by_cat$category == "candy" , ]
data_popcorn_peanuts_seeds_related_snacks <- data_train_tokenized_description_grouped_by_cat[data_train_tokenized_description_grouped_by_cat$category == "popcorn_peanuts_seeds_related_snacks" , ]

#data_train_tokenized_description_grouped_by_cat$word <- factor(data_train_tokenized_description_grouped_by_cat$word)
#create_report(data = data_train_tokenized_description_grouped_by_cat, y = "n")
#ExpReport(data_chocolate, Target = "word", op_file = "Report.html", op_dir = getwd())
```

```{r}
data_train_tokenized_description_2_tokens <- data_food_train %>% unnest_tokens(bigram, description, token = "ngrams", n = 2) %>% count(category, bigram, sort = TRUE)
data_train_tokenized_description_grouped_by_cat_2_tokens <- data_train_tokenized_description_2_tokens %>% group_by(category) %>% summarise(bigram, n)
data_popcorn_2_tokens <- data_train_tokenized_description_grouped_by_cat_2_tokens[data_train_tokenized_description_grouped_by_cat_2_tokens$category == "popcorn_peanuts_seeds_related_snacks" , ]
data_chocolate_2_tokens <- data_train_tokenized_description_grouped_by_cat_2_tokens[data_train_tokenized_description_grouped_by_cat_2_tokens$category == "chocolate" , ]
```

```{r}
data_train_tokenized_ingredients <- data_food_train %>% unnest_tokens(word, ingredients) %>% count(category, word, sort = TRUE)
data_train_tokenized_ingredients_grouped_by_cat <- data_train_tokenized_ingredients %>% group_by(category) %>% summarise(word, n)
```

```{r}
data_chocolate_ingrediends <- data_train_tokenized_ingredients_grouped_by_cat[data_train_tokenized_ingredients_grouped_by_cat$category == "chocolate" , ]
data_candy_ingrediends <- data_train_tokenized_ingredients_grouped_by_cat[data_train_tokenized_ingredients_grouped_by_cat$category == "candy" , ]
```

```{r}
data_train_tokenized_ingredients_ngrams_5 <- data_food_train %>% unnest_tokens(word, ingredients, token = "ngrams", n = 5) %>% count(category, word, sort = TRUE)
data_train_tokenized_ingredients_grouped_by_cat_ngrams_5 <- data_train_tokenized_ingredients_ngrams_5 %>% group_by(category) %>% summarise(word, n)
```

```{r}
merged_df_nutrients <- merged_df_nutrients[-1]
```

```{r}
data_food_test$category <- "unknown"
data_food <- rbind(data_food_train, data_food_test)
merged_df_nutrients <- merge(merged_df_nutrients, data_food[c(1,8)], by = "idx", all.x = TRUE)
```

```{r}
# Grouping by 'category' and 'name', then calculating the mean of 'amount'
df_nutrients_mean_by_cat <- merged_df_nutrients %>%
  group_by(category, name) %>%
  mutate(mean_amount = mean(amount))
```

```{r}
nuts_splitted_by_cat <- split(merged_df_nutrients , merged_df_nutrients$category)
# creating a df for each category
cakes_nutrients <- nuts_splitted_by_cat$cakes_cupcakes_snack_cakes
choco_nutrients <- nuts_splitted_by_cat$chocolate
popcorn_nutrients <- nuts_splitted_by_cat$popcorn_peanuts_seeds_related_snacks
candy_nutrients <- nuts_splitted_by_cat$candy
chips_nutrients <- nuts_splitted_by_cat$chips_pretzels_snacks
cookies_nutrients <- nuts_splitted_by_cat$cookies_biscuits
test_nutrients <- nuts_splitted_by_cat$unknown
```

```{r}
cakes_mean_by_nut <- cakes_nutrients %>% group_by(name) %>% reframe(mean_amount = mean(amount)) 
choco_mean_by_nut <- choco_nutrients %>% group_by(name) %>% reframe(mean_amount = mean(amount))
popcorn_mean_by_nut <- popcorn_nutrients %>% group_by(name) %>% reframe(mean_amount = mean(amount))
candy_mean_by_nut <- candy_nutrients %>% group_by(name) %>% reframe(mean_amount = mean(amount))
chips_mean_by_nut <- chips_nutrients %>% group_by(name) %>% reframe(mean_amount = mean(amount))
cookies_mean_by_nut <- cookies_nutrients %>% group_by(name) %>% reframe(mean_amount = mean(amount))
test_mean_by_nut <- test_nutrients %>% group_by(name) %>% reframe(mean_amount = mean(amount))
```

```{r}
cakes_num_nutrients <- cakes_nutrients %>% group_by(idx) %>% reframe(num_nutrients = length(name))
choco_num_nutrients <- choco_nutrients %>% group_by(idx) %>% reframe(num_nutrients = length(name))
popcorn_num_nutrients <- popcorn_nutrients %>% group_by(idx) %>% reframe(num_nutrients = length(name))
candy_num_nutrients <- candy_nutrients %>% group_by(idx) %>% reframe(num_nutrients = length(name))
chips_num_nutrients <- chips_nutrients %>% group_by(idx) %>% reframe(num_nutrients = length(name))
cookies_num_nutrients <- cookies_nutrients %>% group_by(idx) %>% reframe(num_nutrients = length(name))
test_num_nutrients <- test_nutrients %>% group_by(idx) %>% reframe(num_nutrients = length(name))
```

```{r}
plots_func_num_nutriens_by_cat <- function(x, title_name) {
  hist(x$num_nutrients, main = title_name)
}
```

```{r}
plots_func_num_nutriens_by_cat(cakes_num_nutrients, "cakes_num_nutrients")
plots_func_num_nutriens_by_cat(choco_num_nutrients, "choco_num_nutrients")
plots_func_num_nutriens_by_cat(popcorn_num_nutrients, "popcorn_num_nutrients")
plots_func_num_nutriens_by_cat(candy_num_nutrients, "candy_num_nutrients")
plots_func_num_nutriens_by_cat(chips_num_nutrients, "chips_num_nutrients")
plots_func_num_nutriens_by_cat(cookies_num_nutrients, "cookies_num_nutrients")
plots_func_num_nutriens_by_cat(test_num_nutrients, "test_num_nutrients")
```

```{r}
# creating boxplots
boxplot(cakes_num_nutrients$num_nutrients, choco_num_nutrients$num_nutrients, popcorn_num_nutrients$num_nutrients, candy_num_nutrients$num_nutrients, chips_num_nutrients$num_nutrients, cookies_num_nutrients$num_nutrients, test_num_nutrients$num_nutrients, main = "boxplot for num nutrients per category", names = c("cakes", "chocolate", "popcorn", "candy", "chips", "cookies", "test"))
```

```{r}
# create a df of the nutrients 
m <- merge(cakes_mean_by_nut,candy_mean_by_nut, by = "name", all = TRUE)
m <- merge(m,popcorn_mean_by_nut, by = "name", all = TRUE)
m <- merge(m,choco_mean_by_nut, by = "name", all = TRUE)
m <- merge(m,chips_mean_by_nut, by = "name", all = TRUE)
m <- merge(m,cookies_mean_by_nut, by = "name", all = TRUE)
nutrients_mean_amount_with_zero_amounts <- merge(m,test_mean_by_nut, by = "name", all = TRUE) 
colnames(nutrients_mean_amount_with_zero_amounts) <- c("nutrient", "cakes", "candy", "popcorn", "chocolate", "chips", "cookies", "test")
# replace NAs with 0
nutrients_mean_amount_with_zero_amounts[is.na(nutrients_mean_amount_with_zero_amounts)] <- 0  
rownames(nutrients_mean_amount_with_zero_amounts) <- nutrients_mean_amount_with_zero_amounts[,1]
#nutrients_mean_amount_with_zero_amounts <- nutrients_mean_amount_with_zero_amounts[,-1]
```
```{r}
ggplot_nutrients <- function(pivoted_df, start, end) {
  ggplot(data = pivoted_df[start:end,], mapping = aes(x = category, y = mean_amount, color = category)) + geom_point() +
  facet_wrap(. ~ nutrient, scales = "free_y") +
  labs(title = "category vs. nutrient mean amount of each nutrient",
       #subtitle = "Faceted by nutrient",
       x = "category", y ="mean_amount") + 
  theme(strip.text.x = element_text(size = 10, margin = margin()), axis.text.x.bottom = element_blank(), strip.text.y = element_text(size = 20, margin = margin()))
}
```



```{r}
nuts_pivoted <- nutrients_mean_amount_with_zero_amounts %>% pivot_longer(!nutrient, names_to = "category", values_to = "mean_amount")
ggplot_nutrients(nuts_pivoted, 1, 63)
ggplot_nutrients(nuts_pivoted, 64, 126)
ggplot_nutrients(nuts_pivoted, 127, 189)
ggplot_nutrients(nuts_pivoted, 190, 252)
ggplot_nutrients(nuts_pivoted, 253, 329)
```


```{r}
#transpoze the df
transpozed_mean_amount_with_zero_amounts <- as.data.frame( t(nutrients_mean_amount_with_zero_amounts) )
colnames(transpozed_mean_amount_with_zero_amounts) <- transpozed_mean_amount_with_zero_amounts[1,]
transpozed_mean_amount_with_zero_amounts <- transpozed_mean_amount_with_zero_amounts[-1,]
transpozed_mean_amount_with_zero_amounts <- as.data.frame(sapply(transpozed_mean_amount_with_zero_amounts, as.numeric))
rownames(transpozed_mean_amount_with_zero_amounts) <- c("cakes", "candy", "popcorn", "chocolate", "chips", "cookies", "test")
```

